### ISSUE TITLE
Add cryptography to stored url

### ISSUE THREAD

**Issue by Remeic** [Remeic/Squozy#3]
You can implement encryption on the url to the database so that the administrator opening the database does not see the clear url

#hacktoberfest

**Comment by angelbarrera92** [comment]
Hi!
I want to work on it... but... i don't know exactly what you're looking for...
Do you want to hide the db parameters? If you externalize those values into environment variables so the administrator must know the correct values in order to get running the APP. 

Also, heroku provides a way to add environment variables. The change is compatible.

**Comment by angelbarrera92** [comment]
Ive got the solution. 
I will send you a PR ASAP!

**Comment by Remeic** [comment]
No problem, be calm, assign this issue to you
Thanks in advance

**Comment by angelbarrera92** [comment]
PR #5 sent. 

Let me know if that solves your problem!

**Comment by Remeic** [comment]
Thanks to @angelbarrera92, from db url is crypted, thanks again, this issue is closed
